{{- if .Values.gpuExporter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "accelera.gpuExporter.serviceAccountName" . }}
  labels:
    {{- include "accelera.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpu-exporter
{{- end }}
